Update codeowners
gardener/terraformer pull request #100
Opened 2021-07-21 09:31 UTC by dkistner

**How to categorize this PR?**

/kind enhancement
/priority normal

**What this PR does / why we need it**:
Add extension maintainers as codeowners for the respective Terraform provider plugin configurations.

**Release note**:

```NONE

```

/invite @timebertt  @ialidzhikov @vpnachev
/cc @kon-angelo @minchaow @MartinWeindel @prashanth26 @rfranzke

2021-07-21 10:01 UTC, vpnachev requested changes

2021-07-21 10:01 UTC, vpnachev commented on CODEOWNERS
> +/build/all/**       @gardener-extension-provider-alicloud-maintainers @gardener-extension-provider-aws-maintainers @gardener-extension-provider-azure-maintainers @gardener-extension-provider-gcp-main
```suggestion
/build/all/**       @gardener/gardener-maintainers @gardener-extension-provider-alicloud-maintainers @gardener-extension-provider-aws-maintainers @gardener-extension-provider-azure-maintainers @gardener-extension-provider-gcp-maintainers @gardener-extension-provider-openstack-maintainers
```

2021-07-21 10:05 UTC, dkistner commented on CODEOWNERS
> +/build/all/**       @gardener-extension-provider-alicloud-maintainers @gardener-extension-provider-aws-maintainers @gardener-extension-provider-azure-maintainers @gardener-extension-provider-gcp-main
done

2021-07-21 10:08 UTC, vpnachev approved these changes
/lgtm
/squash

2021-07-22 07:14 UTC, timebertt approved these changes
/lgtm

2021-07-26 06:18 UTC, dkistner commented
Can we go on and merge this one?

2021-07-26 06:28 UTC, vpnachev commented
Please, ensure the PR checks are successful. Until then we cannot merge this PR.

2021-07-26 06:28 UTC, jia-jerry commented
/lgtm

2021-07-26 07:00 UTC, dkistner commented
/ok-to-test

2021-07-26 07:07 UTC, dkistner commented
/reviewed ok-to-test

2021-07-26 07:37 UTC, merged